name: MCBooster
version: 2.0
main: br.com.mcbooster.MCBooster
authors: [TequilAxBr, RUSH]

commands:
  givebooster:
    aliases: [gb]
    description: Envia um Booster para um player.
    permission: booster.admin
  booster:
    description: Mostra informações sobre o seu Booster.